version: '{build}-{branch}'
image: Visual Studio 2019

clone_depth: 1

init:
- ps: |
    function craft() {
        & C:\python36\python.exe "C:\CraftMaster\CraftMaster\CraftMaster.py" --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    Write-Host $env:APPVEYOR_BUILD_FOLDER
    & cmd /C "git clone -q --depth=1 https://invent.kde.org/packaging/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    & cmd /C "git clone https://gitlab.freedesktop.org/poppler/test.git $env:APPVEYOR_BUILD_FOLDER/../test 2>&1"
    craft craft
    craft --install-deps poppler

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER poppler

after_build:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER --package poppler

test_script:
- ps: |
   craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test poppler
   
artifacts:
  - path: cache\**\.*
  - path: binaries\*   
  - path: $env:APPVEYOR_BUILD_FOLDER
  - path: poppler


environment:
    matrix:
    - TARGET: windows-mingw_64-gcc
    - TARGET: windows-msvc2019_64-cl
