version: '{build}-{branch}'
image: Visual Studio 2019

clone_depth: 1

init:
- ps: |
    function craft() {
        & C:\python36\python.exe "C:\CraftMaster\CraftMaster\CraftMaster.py" --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    Write-Host $env:APPVEYOR_BUILD_FOLDER
    Write-Host $env:APPVEYOR_BUILD_FOLDER | Out-File -FilePath cache/ps_output
    & cmd /C "git clone -q --depth=1 https://invent.kde.org/packaging/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    & cmd /C "git clone https://gitlab.freedesktop.org/poppler/test.git $env:APPVEYOR_BUILD_FOLDER/../test 2>&1"
    craft craft
    craft --install-deps poppler

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER poppler
    Tree C: /F | Set-Content cache\tree1.txt
    Tree C: /F | Set-Content binaries\tree1.txt
    Tree C: /F | Set-Content poppler\tree1.txt

after_build:
- ps: |
    Tree C: /F | Set-Content cache\tree2.txt
    Tree C: /F | Set-Content binaries\tree2.txt
    Tree C: /F | Set-Content poppler\tree2.txt
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER --package poppler
    Tree C: /F | Set-Content cache\tree3.txt
    Tree C:\ /F | Set-Content cache\tree3b.txt
    Tree ..\..\ /F | Set-Content cache\tree3c.txt
    Tree C: /F | Set-Content binaries\tree3.txt
    Tree C: /F | Set-Content poppler\tree3.txt

test_script:
- ps: |
   craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test poppler
   
artifacts:
  - path: cache\**\.*
  - path: binaries\*
  - path: poppler


environment:
    matrix:
    - TARGET: windows-mingw_64-gcc
    - TARGET: windows-msvc2019_64-cl
